version: '3.7'
services:
  database:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - grupo99
  application:
    image: node:16-alpine
    volumes:
      - ./:/backend
    working_dir: /backend
    container_name: be_grupo99
    env_file: .env
    expose:
      - '3000'
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database
    command: ash -c "npm ci && npm run dev"
    networks:
      - grupo99
networks:
  grupo99:
    external: false
    driver: bridge